apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: grafana-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-dep
spec:
  template:
    metadata:
      name: grafana
      labels:
        app: grafana-app
    spec:
      containers: 
        - name: grafana
          image: grafana_image
          ports:
            - name: grafana
              containerPort: 3000
          livenessProbe:
            exec:
              command:
                - sh
                - /check.sh
            initialDelaySeconds: 30
            periodSeconds: 10
          imagePullPolicy: Never
  replicas: 1
  selector:
    matchLabels:
      app: grafana-app