apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
spec:
  type: ClusterIP
  clusterIP: 10.99.10.10
  selector:
    app: mysql-app
  ports:
      - port: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-dep
spec:
  template:
    metadata:
      name: mysql
      labels:
        app: mysql-app
    spec:
      containers: 
        - name: mysql
          image: mysql_image
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: "/var/lib/mysql"
              name: mysql
          livenessProbe:
            exec:
              command:
                - sh
                - /check.sh
            initialDelaySeconds: 30
            periodSeconds: 10
          imagePullPolicy: Never
      volumes:
        - name: mysql
          hostPath:
            path: /mnt/mysql
            type: Directory
  replicas: 1
  selector:
    matchLabels:
      app: mysql-app