apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: pma-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-dep
spec:
  template:
    metadata:
      name: phpmyadmin
      labels:
        app: pma-app
    spec:
      containers: 
        - name: phpmyadmin
          image: php_image
          ports:
            - containerPort: 5000
          livenessProbe:
            exec:
              command:
                - sh
                - /check.sh
            initialDelaySeconds: 30
            periodSeconds: 10
          imagePullPolicy: Never
  replicas: 1
  selector:
    matchLabels:
      app: pma-app