apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress-app
spec:
  ports:
    - port: 5050
      targetPort: 5050
      protocol: TCP
      name: wordpress-app
  selector:
    app: wordpress
  type: LoadBalancer
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-dep
  labels:
    app: wordpress-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress-app
  template:
    metadata:
      labels:
        app: wordpress-app
    spec:
      containers:
      - name: wordpress
        image: wordpress_image
        ports:
        - containerPort: 5050