apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type: LoadBalancer
  ports:
  - port: 5050
    targetPort: 5050
  selector:
    app: wodpress-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-dep
spec:
  template:
    metadata:
      name: wordpress
      labels:
        app: wodpress-app
    spec:
      containers: 
        - name: wordpress
          image: wordpress_image
          ports:
            - containerPort: 5050
          livenessProbe:
            exec:
              command:
                - sh
                - /check.sh
            initialDelaySeconds: 30
            periodSeconds: 10
          imagePullPolicy: Never
  replicas: 1
  selector:
    matchLabels:
      app: wodpress-app